lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'  # Chemin vers la clé privée
    public_key: '%kernel.project_dir%/config/jwt/public.pem'    # Chemin vers la clé publique
    pass_phrase: 'gloom'                                             # Si tu as utilisé une phrase secrète lors de la génération des clés
    token_ttl: 36000                                             # Durée de validité du token (en secondes)
