security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        

        # Firewall pour json_login et l'inscription
        public:
            pattern: ^/api/auth
            stateless: true
            security: false  # Pas d'authentification nécessaire pour ces routes

        # # Firewall pour la connexion via json_login
        # login:
        #     pattern: ^/api/auth/login
        #     stateless: true
        #     json_login:
        #         check_path: /api/auth/login
        #         username_path: email
        #         password_path: password
        #         success_handler: lexik_jwt_authentication.handler.authentication_success
        #         failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Firewall pour les routes protégées par JWT
        api:
            pattern: ^/api/
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
         # Autoriser l'accès anonyme aux routes d'inscription et de connexion
        - { path: ^/api/auth/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # # Autoriser les requêtes GET sans authentification pour toutes les routes
        # - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }

         # Protéger les routes POST, PUT, DELETE de l'entité User et toutes les autres routes API
        - { path: ^/api/user, roles: IS_AUTHENTICATED_FULLY, methods: [POST, PUT, DELETE] }
        - { path: ^/api/user/.*, roles: IS_AUTHENTICATED_FULLY, methods: [POST, PUT, DELETE] }

        # Protéger les routes POST, PUT, DELETE des instruments et toutes les autres routes API
        # - { path: ^/api, roles: IS_AUTHENTICATED_FULLY, methods: [POST, PUT, DELETE] }
        - { path: ^/api/instruments, roles: IS_AUTHENTICATED_FULLY, methods: [POST, PUT, DELETE] }
        - { path: ^/api/instruments/.*, roles: IS_AUTHENTICATED_FULLY, methods: [POST, PUT, DELETE] }

